version: '3.3'
services:
  app:
    image: registry.heroku.com/injury-log/web
    ports:
      - 8080:8080
    env_file:
      - .env
    environment:
      MICRONAUT_ENVIRONMENTS: docker
    depends_on:
      - database

  database:
    image: postgres:11-alpine
    environment:
      POSTGRES_USER: injury-log
      POSTGRES_PASSWORD: injury-log
      POSTGRES_DB: injury-log

  test:
    image: adoptopenjdk:11.0.5_10-jdk-hotspot
    command: /bin/sh -c './gradlew test'
    working_dir: /src
    volumes:
      - .:/src
    env_file:
      - .env
