datasources:
  default:
    url: ${JDBC_DATABASE_URL}
    driverClassName: org.postgresql.Driver
    schema-generate: CREATE_DROP

aws:
  key: ${AWS_ACCESS_KEY_ID}
  secret: ${AWS_SECRET_KEY}
  s3:
    region: ${AWS_S3_REGION}
    bucket: ${AWS_S3_BUCKET}
