micronaut:
  application:
    name: injurylog
  security:
    enabled: true
    endpoints:
      login:
        enabled: true
      oauth:
        enabled: true
    token:
      jwt:
        enabled: true
        signatures:
          secret:
            generator:
              secret: ${JWT_SIGNATURES_GENERATOR_SECRET}

datasources:
  default:
    url: jdbc:h2:mem:devDb
    driverClassName: org.h2.Driver
    username: sa
    password: ''
    schema-generate: CREATE_DROP
    dialect: H2

jpa:
  default:
    properties:
      hibernate:
        bytecode:
          provider: none
        hbm2ddl:
          auto: update
        show_sql: true

google:
  android:
    client:
      id: 588170906559-raeponfqqduusmmpnqjd8a422ccq8cp0.apps.googleusercontent.com
  web:
    client:
      id: 588170906559-30feberacr881j2v45n3bf6grmm4kpdd.apps.googleusercontent.com

users:
  admin:
    # NOTE: Must be associated with a valid Google account
    email: ${ADMIN_USER_EMAIL}
    password: ${random.uuid}
  test:
    # NOTE: This doesn't have to be a valid email
    email: test@test.com
    password: ${random.uuid}

aws:
  key: ${AWS_ACCESS_KEY_ID}
  secret: ${AWS_SECRET_KEY}
  s3:
    region: ${AWS_S3_REGION}
    bucket: ${AWS_S3_BUCKET}
