name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container: adoptopenjdk:11.0.5_10-jdk-hotspot

    steps:
    - uses: actions/checkout@v1
    - name: Test
      run: ./gradlew --stacktrace test
      env:
        ADMIN_USER_EMAIL: ${{ secrets.ADMIN_USER_EMAIL }}
        JWT_SIGNATURES_GENERATOR_SECRET: ${{ secrets.JWT_SIGNATURES_GENERATOR_SECRET }}
    - name: Archive test results
      uses: actions/upload-artifact@v1
      with:
        name: test-report
        path: build/reports/tests/test/
