name: CI

on: [push]

jobs:
  cicd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '11.0.5'

      - name: Test
        run: ./gradlew test
        env:
          ADMIN_USER_EMAIL: ${{ secrets.ADMIN_USER_EMAIL }}
          ADMIN_USER_PASSWORD: ${{ secrets.ADMIN_USER_PASSWORD }}
          JWT_SIGNATURES_GENERATOR_SECRET: ${{ secrets.JWT_SIGNATURES_GENERATOR_SECRET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
          AWS_S3_REGION: ${{ secrets.AWS_S3_REGION }}
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}

      - name: Archive test results
        if: always()
        uses: actions/upload-artifact@v1
        with:
          name: test-report
          path: build/reports/tests/test/

      - name: Login to Heroku Container registry
        if: github.ref == 'refs/heads/release'
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku container:login

      - name: Build and push
        if: github.ref == 'refs/heads/release'
        run: ./gradlew jib

      - name: Release
        if: github.ref == 'refs/heads/release'
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku container:release web -a injury-log
