name: CI

on: [push]

jobs:
  test_and_build:
    runs-on: ubuntu-latest
    container: adoptopenjdk:11.0.5_10-jdk-hotspot

    steps:
    - uses: actions/checkout@v1
    - name: Test
      run: ./gradlew test
      env:
        ADMIN_USER_EMAIL: ${{ secrets.ADMIN_USER_EMAIL }}
        ADMIN_USER_PASSWORD: ${{ secrets.ADMIN_USER_PASSWORD }}
        JWT_SIGNATURES_GENERATOR_SECRET: ${{ secrets.JWT_SIGNATURES_GENERATOR_SECRET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID}}
        AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
        AWS_S3_REGION: ${{ secrets.AWS_S3_REGION }}
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
    - name: Archive test results
      if: always()
      uses: actions/upload-artifact@v1
      with:
        name: test-report
        path: build/reports/tests/test/

  deploy:
    if: github.ref == 'refs/heads/release'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Login to Heroku Container registry
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: docker login --username=_ --password=$HEROKU_API_KEY registry.heroku.com
      - name: Build and push
        run: ./gradlew jib
      - name: Release
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku container:release -a ${{ secrets.HEROKU_APP_NAME }} web
