name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container: adoptopenjdk:11.0.5_10-jdk-hotspot

    steps:
    - uses: actions/checkout@v1
    - name: Test
      run: ./gradlew --stacktrace test
      env:
        ADMIN_USER_EMAIL: ${{ secrets.ADMIN_USER_EMAIL }}
        JWT_SIGNATURES_GENERATOR_SECRET: ${{ secrets.JWT_SIGNATURES_GENERATOR_SECRET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID}}
        AWS_SECRET_KEY: ${{ secrets. AWS_SECRET_KEY }}
        AWS_S3_REGION: ${{ secrets. AWS_S3_REGION }}
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
    - name: Archive test results
      if: always()
      uses: actions/upload-artifact@v1
      with:
        name: test-report
        path: build/reports/tests/test/
