name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
#    container: adoptopenjdk/openjdk12-openj9
    container: adoptopenjdk:11.0.5_10-jdk-openj9-0.17.0-bionic

    steps:
    - uses: actions/checkout@v1
    - name: Test
      run: ./gradlew --stacktrace test
      env:
        ADMIN_USER_EMAIL: ${{ secrets.ADMIN_USER_EMAIL }}
        JWT_SIGNATURES_GENERATOR_SECRET: ${{ secrets.JWT_SIGNATURES_GENERATOR_SECRET }}
